### ISSUE TITLE
/home/kali/1/outfile.nim(3, 8) Error: cannot open file: winim

### ISSUE THREAD

**Issue by Yihsiwei** [evilashz/NimFileBinder#1]
linux AND windows /home/kali/1/outfile.nim(3, 8) Error: cannot open file: winim
outfile.nim(3, 8) Error: cannot open file: winim
outfile.nim(3, 8) Error: cannot open file: winim
outfile.nim(3, 8) Error: cannot open file: winim
outfile.nim(3, 8) Error: cannot open file: winim
outfile.nim(3, 8) Error: cannot open file: winim

**Comment by evilashz** [comment]
Hi,the reason about this is the template code lacks the winim library, you could install this by the command 
`nimble install winim`

**Comment by Yihsiwei** [comment]
> Hi,the reason about this is the template code lacks the winim library, you could install this by the command `nimble install winim`

Thank you very much for your answer, which helped me solve the problem. But I have another question. Why can't I download from the command line

Like this

```
C:\Users\10702>nimble install winim
    Prompt: winim not found in any local packages.json, check internet for updated packages? [y/N]
    Answer:
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Package not found.

C:\Users\10702>nimble install winim
    Prompt: winim not found in any local packages.json, check internet for updated packages? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
       Tip: 7 messages have been suppressed, use --verbose to show them.
     Error: Package not found.

```

**Comment by Yihsiwei** [comment]
> Hi,the reason about this is the template code lacks the winim library, you could install this by the command `nimble install winim`

I always download them from GitHub. Put it in the same folder. I hope you have a better way
like this
![image](https://user-images.githubusercontent.com/59053987/139569152-a1acd2b3-ae4d-4e24-af86-fddb2c181a32.png)

**Comment by evilashz** [comment]
you could put this command like this
`nimble install https://github.com/khchen/winim`
And.. by the way , there is one more thing  is that I recommend you to use Linux or unix (Kali or Mac)to use the NimFileBinder
Because the encrypto library `nimcrypto` which my code used may cause a problem like the files after encryption will be different if use NimFileBinder in Windows
Sorry, thin is a strange issue of my code, However I think the problem is the reason for the compatibility of the nimcrypto library and the reason of this is i use it by standred way -.-

**Comment by Yihsiwei** [comment]
> you could put this command like this `nimble install https://github.com/khchen/winim` And.. by the way , there is one more thing is that I recommend you to use Linux or unix (Kali or Mac)to use the NimFileBinder Because the encrypto library `nimcrypto` which my code used may cause a problem like the files after encryption will be different if use NimFileBinder in Windows Sorry, thin is a strange issue of my code, However I think the problem is the reason for the compatibility of the nimcrypto library and the reason of this is i use it by standred way -.-

THANK YOU.
